### ISSUE TITLE
Add good favicon

### ISSUE THREAD

**Issue by schedutron** [schedutron/home-server#14]

**Comment by kir-aan** [comment]
I want to work on this issue

**Comment by schedutron** [comment]
@sai8kiran99 Go for it!

**Comment by km4** [comment]
I take this issues, 
Generate favicon ;)

**Comment by milanojs** [comment]
do we have an image for that?

**Comment by km4** [comment]
<img width="305" alt="zrzut ekranu 2017-10-29 o 15 49 09" src="https://user-images.githubusercontent.com/1108808/32144936-fe3d2d62-bcc0-11e7-8605-c24f97be7b18.png">

#23

**Comment by schedutron** [comment]
@milanojs Nope. I'll give out a new issue soon. Try that out, this has been resolved :)
