### ISSUE TITLE
Add screenshots to README

### ISSUE THREAD

**Issue by schedutron** [schedutron/home-server#2]

**Comment by pjhampton** [comment]
I can take this.

**Comment by pjhampton** [comment]
I have taken these two screenshots.

![screen1](https://user-images.githubusercontent.com/8960296/32135055-789435d2-bbf0-11e7-9d52-05a6c2a7c1a8.png)
![screen2](https://user-images.githubusercontent.com/8960296/32135056-78b3ac50-bbf0-11e7-96db-eb2fe7a7cca4.png)

**Comment by schedutron** [comment]
They're good, but they would be better if you provide a movie with a more humane title, not a code like "IMG _0684". Rest is awesome! Make these changes and commit!

**Comment by pjhampton** [comment]
Sure, thing. I don't have any other vids on my machine unfortunately so it will be this, but I can certainly remain. PR incoming 👍

**Comment by schedutron** [comment]
You mean rename, right? Can't wait for the PR!

**Comment by pjhampton** [comment]
Ok, how is this @schedutron?

![vid1](https://user-images.githubusercontent.com/8960296/32135160-586dd54a-bbf2-11e7-891f-02039f32d0a1.png)
![vid2](https://user-images.githubusercontent.com/8960296/32135161-58899ef6-bbf2-11e7-8a0c-9cf059514f45.png)

**Comment by schedutron** [comment]
Awesome. For now, make a PR for this and I will accept, but perhaps I would have to modify these in the future once the front-end of the app updates. Thanks!

**Comment by mohan-mu** [comment]
https://github.com/mohan-mu/home-server/blob/master/README.md

**Comment by schedutron** [comment]
@pjhampton Please make a commit so that I can pull your original contributions.

**Comment by pjhampton** [comment]
@schedutron I did - https://github.com/schedutron/home-server/pull/3
