### ISSUE TITLE
Update Screenshots in README

### ISSUE THREAD

**Issue by schedutron** [schedutron/home-server#7]
The front-end design has evolved but the README still shows the old, boring design. Update the screenshots in README to show the updated design.

**Comment by schedutron** [comment]
@Kalwing Why not add your screenshots here?

**Comment by GingerDragon7** [comment]
i want to work on this

**Comment by schedutron** [comment]
@GingerDragon7 Sure. Just do it!

**Comment by allan9595** [comment]
I will try this one

**Comment by airqz** [comment]
fix it, add new README 

<img width="1920" alt="screenshot1" src="https://user-images.githubusercontent.com/10780151/32139461-d67ff380-bc49-11e7-9d9b-ae580196b754.png">
<img width="1920" alt="screenshot2" src="https://user-images.githubusercontent.com/10780151/32139462-d6994e16-bc49-11e7-96aa-bd7965226d6a.png">

**Comment by schedutron** [comment]
@airqz Looks good!
